### ISSUE TITLE
DIYbiosphere

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/sphere#205]
[DIYbiosphere](http://sphere.diybio.org/projects/DIYbiosphere/) is an open source project to connect DIYbio initiatives from all over the world

**Comment by jasonbobe** [comment]
I just added geolocation to your entry. this is required in order to show
up on the map. May still take a day to show-up, but this should fix the
problem.

**Comment by DiyBiook** [comment]
Hi, I dont know why, but we still dont appear in the map, Can you help us to appear in the map before the bbkopenscience.com event?

**Comment by sabgaby** [comment]
Hey @DiyBiook, I am moving this issue to another ticket: #232

**Comment by 100ideas** [comment]
this was resolved in #232
